package de.blutmondgilde.changeloggenerator.model;

import de.blutmondgilde.changeloggenerator.utils.CurseForgeAPI;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

public class ModpackChanges {

    private final List<ModFile> newMods = new ArrayList<>();

    private final List<ModFile> changedMods = new ArrayList<>();

    private final List<ModFile> removedMods = new ArrayList<>();
    private final CurseForgeAPI api;

    public ModpackChanges(ModpackFile oldPack, ModpackFile newPack, String token) {
        this.api = new CurseForgeAPI(token);
        List<ModFile> oldMods = new ArrayList<>(Arrays.asList(oldPack.getFiles()));
        List<ModFile> newMods = Arrays.asList(newPack.getFiles());

        newMods.forEach(mod -> {
            Optional<ModFile> oldModData = oldMods.stream()
                .filter(modFile -> modFile.getProjectID() == mod.getProjectID())
                .findFirst();
            if (oldModData.isPresent()) {
                if (oldModData.get().getFileID() != mod.getFileID()) {
                    this.changedMods.add(mod); //Add changed
                }
                oldMods.remove(oldModData.get());
            } else {
                this.newMods.add(mod); //Add new
            }
        });

        removedMods.addAll(oldMods); //Add removed
    }

    public String getChanges() {
        StringBuilder builder = new StringBuilder("# New Mods:\n");
        applyListData(builder, newMods);
        builder.append("\n# Changed Mods:\n");
        applyListData(builder, changedMods);
        builder.append("\n# Removed Mods:\n");
        applyListData(builder, removedMods);
        builder.append("\n\n").append("Changelog generated by [CF-Changelog-Generator](https://github.com/Charismara/CF-Changelog-Generator)");
        return builder.toString();
    }

    private void applyListData(StringBuilder builder, List<ModFile> files) {
        files.forEach(file -> {
            CFMod mod = this.api.getModInformation(file);
            builder.append("## [").append(mod.getName()).append("](https://www.curseforge.com/minecraft/mc-mods/").append(mod.getSlug()).append(")\n");
            builder.append(this.api.getModChangeLog(file)).append("\n\n");
        });
    }
}
